# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT classmanager.wsgi

beta_settings:
  cloud_sql_instances: equest-292122:us-central1:myinstance

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
  cpu_utilization:
    target_utilization: 0.5
network: {}
  # [END runtime]z