# Generated by Django 3.0.6 on 2020-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='blog_1images/defaultblog.jpg', upload_to='blog_1images/'),
        ),
    ]
